### ISSUE TITLE
analysis-emoji 5.2.2 was designed for 5.0.0?

### ISSUE THREAD

**Issue by jattenberg** [jolicode/emoji-search#14]
trying to install with my 5.2.2 version of ES:

```
Neptune-2:elasticsearch-5.2.2$ bin/elasticsearch-plugin install https://github.com/jolicode/emoji-search/releases/download/5.2.2/analysis-emoji-5.2.2.zip -v
-> Downloading https://github.com/jolicode/emoji-search/releases/download/5.2.2/analysis-emoji-5.2.2.zip
Retrieving zip from https://github.com/jolicode/emoji-search/releases/download/5.2.2/analysis-emoji-5.2.2.zip
[=================================================] 100%
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [analysis-emoji] is incompatible with Elasticsearch [5.2.2]. Was designed for version [5.0.0]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:108)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:421)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:486)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:195)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

is there any work-around or change i can make to fix this?

**Comment by damienalexandre** [comment]
Just published a new release, you can try:

```
bin/elasticsearch-plugin install https://github.com/jolicode/emoji-search/releases/download/5.2.2.1/analysis-emoji-5.2.2.1.zip
```

Ref #10, my release process is so broken that I forgot to bump a version number (the gradle one). Sorry for the mistake :sob: and thank for reporting it!

**Comment by fredigogo** [comment]
Hello Damien, I've just tried installing the 5.1.1 version and I get the same error as described here. It says the version was designed for 5.0.0. I would suppose other versions of the plugin have the same issue. Thank you.

**Comment by damienalexandre** [comment]
Hi, thanks for the heads up! I just rebuild the proper 5.1.1 release, can you try again?

https://github.com/jolicode/emoji-search/releases/tag/5.1.1

**Comment by fredigogo** [comment]
@damienalexandre working fine now! Thank you for the fast response.
